### PR TITLE
My First Website :) (NO CSS)

### PR DESCRIPTION
**Pull request by AlexDvalishvili1**
Easy

### CODE REVIEW

**Comment by AlexDvalishvili1** [comment]
Well done <3

**Comment by AlexDvalishvili1** [comment]
Best work i have ever seen

**Comment by AlexDvalishvili1** [comment]
Alex i am your fan

**Comment by AlexDvalishvili1** [comment]
Alex you are the best thank you for everything

**Review by maks-io — APPROVED** [review]

**Pull request merged**
